/**
 * SeedData.gs
 * -----------
 * One-time seed data pulled from Matteo's dad's most recent payroll export
 * (week ending 2026-09-05). This only gets written into the spreadsheet the
 * first time setupSheet() is run (see Code.gs) — after that, the Crew and
 * Projects tabs in the spreadsheet are the source of truth, and you edit
 * crew/projects there directly (add new hires, retire old projects, etc.)
 * rather than by editing this file.
 */

var SEED_CREW = [
  { "id": "5997", "name": "Adam Zaretsky", "position": "J" },
  { "id": "7309", "name": "Adrian Leung", "position": "J" },
  { "id": "8041", "name": "Albert Arevalo", "position": "L" },
  { "id": "7082", "name": "Alessio Petrini", "position": "La" },
  { "id": "8431", "name": "AlvinD Barron", "position": "L" },
  { "id": "4179", "name": "Andre H. O'Regan", "position": "F" },
  { "id": "5853", "name": "Andrew Eugene", "position": "La" },
  { "id": "7366", "name": "Andrew Macgillivary", "position": "A5-82.5" },
  { "id": "8364", "name": "Anthony O Rizza", "position": "L" },
  { "id": "7506", "name": "Anthony Pereira", "position": "L" },
  { "id": "7038", "name": "Anthony Tucceri", "position": "L" },
  { "id": "3696", "name": "Antonio Martins", "position": "G" },
  { "id": "6972", "name": "Antonio Pileggi", "position": "J" },
  { "id": "5045", "name": "Ben A Kelly", "position": "La" },
  { "id": "7199", "name": "Benjamin N. Kapps", "position": "J" },
  { "id": "7914", "name": "Blair W Coxhead", "position": "G" },
  { "id": "7311", "name": "Brent Elnor", "position": "L" },
  { "id": "7398", "name": "Brian Martins", "position": "J" },
  { "id": "6127", "name": "Carson Lockhart", "position": "F" },
  { "id": "7750", "name": "Christian Escoto", "position": "L" },
  { "id": "6313", "name": "Daniel Pagano", "position": "F" },
  { "id": "3055", "name": "Danny Gallagher", "position": "G" },
  { "id": "5115", "name": "Dave Niemi", "position": "Est" },
  { "id": "7064", "name": "Dave Salewski", "position": "La" },
  { "id": "7542", "name": "Dave Sposato", "position": "F" },
  { "id": "5765", "name": "David Brown", "position": "J" },
  { "id": "5133", "name": "David Korn", "position": "J-P" },
  { "id": "4599", "name": "David W Clark", "position": "F" },
  { "id": "8208", "name": "Dennis Legay", "position": "L" },
  { "id": "8423", "name": "Deson Moriarity", "position": "Ut1" },
  { "id": "8407", "name": "Dillon McNeil", "position": "Ut1" },
  { "id": "4121", "name": "Dino Bellisario", "position": "J" },
  { "id": "6891", "name": "Domenic F Miranda", "position": "J" },
  { "id": "2966", "name": "Donald L Sisson", "position": "J-P" },
  { "id": "4230", "name": "Elio Minicucci", "position": "J" },
  { "id": "8421", "name": "Eugenio A Merante", "position": "L" },
  { "id": "2679", "name": "Felice F Dipietro", "position": "J" },
  { "id": "5248", "name": "Floyde Rideout", "position": "G" },
  { "id": "2818", "name": "Gaetan Danis", "position": "Lma" },
  { "id": "3661", "name": "George E. Saunders", "position": "G" },
  { "id": "6231", "name": "Giuseppe Bruzzese", "position": "F" },
  { "id": "8014", "name": "Giuseppe Ferreri", "position": "L" },
  { "id": "8013", "name": "Greggory E McIlwaine", "position": "L" },
  { "id": "7696", "name": "Gregory C Soumakis", "position": "J" },
  { "id": "0402", "name": "Horst R Tim", "position": "J-P" },
  { "id": "8201", "name": "Jacob A Niemi", "position": "Pa" },
  { "id": "6406", "name": "James J Archer", "position": "J" },
  { "id": "8365", "name": "Jamie Tanguay", "position": "Ld" },
  { "id": "2531", "name": "Jan De Jong", "position": "F" },
  { "id": "5833", "name": "Jeffrey Philip Sanders", "position": "La" },
  { "id": "6699", "name": "Joe Parisi", "position": "J" },
  { "id": "3326", "name": "John M Sousa", "position": "Lh" },
  { "id": "4936", "name": "John Paolo Mammone", "position": "J" },
  { "id": "6825", "name": "Jon S Brozek", "position": "G" },
  { "id": "6821", "name": "Jonathan Niemi", "position": "F" },
  { "id": "6871", "name": "Jordan C McKinney", "position": "J" },
  { "id": "7947", "name": "Jordan M White", "position": "La" },
  { "id": "7954", "name": "Kalen DA Haggarty", "position": "A2-33.0" },
  { "id": "7293", "name": "Kevin  Carrillo", "position": "J" },
  { "id": "7209", "name": "Kyle AR Thompson", "position": "G" },
  { "id": "8397", "name": "Kyle Peaker", "position": "L" },
  { "id": "6981", "name": "Levi J Niemi", "position": "J" },
  { "id": "7035", "name": "Lorne Checchia", "position": "J" },
  { "id": "7305", "name": "Lucas L. Raposo", "position": "Go" },
  { "id": "7903", "name": "Lucas Vincenzi", "position": "A3-49.5" },
  { "id": "6039", "name": "Marek T Marczewski", "position": "J" },
  { "id": "6535", "name": "Mario Marini", "position": "J" },
  { "id": "6347", "name": "Martin A.J. Bonigut", "position": "G" },
  { "id": "4506", "name": "Matt McMullen", "position": "J" },
  { "id": "6181", "name": "Matthew W McEwen", "position": "J" },
  { "id": "7600", "name": "Michael M Moreland", "position": "L" },
  { "id": "2964", "name": "Michael Palma", "position": "J" },
  { "id": "6062", "name": "Michaele Mele", "position": "J" },
  { "id": "5994", "name": "Mohamed Shah", "position": "G" },
  { "id": "6804", "name": "Nikola Jurkovich", "position": "La" },
  { "id": "7659", "name": "Oleg Stefaniv", "position": "J" },
  { "id": "8076", "name": "Owen Cassarchis", "position": "A1-16.5" },
  { "id": "5883", "name": "Patrick Gaidola", "position": "La" },
  { "id": "6067", "name": "Paul Treasure", "position": "Lh" },
  { "id": "2258", "name": "Ralph H McCabe", "position": "G" },
  { "id": "6549", "name": "Richard D Boyd", "position": "F" },
  { "id": "7553", "name": "Richard Halasz", "position": "L" },
  { "id": "7065", "name": "Robert F McFadden", "position": "La" },
  { "id": "8059", "name": "Robert Zappia", "position": "G" },
  { "id": "7993", "name": "Robin Simonson", "position": "A2-33.0" },
  { "id": "8049", "name": "Ryan O'Leary", "position": "L" },
  { "id": "6219", "name": "Ryan P Niemi", "position": "F" },
  { "id": "5467", "name": "Scott T. Boreham", "position": "Lh" },
  { "id": "4721", "name": "Sean J Wright", "position": "G" },
  { "id": "5695", "name": "Shawn B Walker", "position": "Go" },
  { "id": "6051", "name": "Shawn Robert Ward", "position": "J-P" },
  { "id": "5452", "name": "Sherwin Tinio", "position": "J" },
  { "id": "5785", "name": "Simon Hotari", "position": "F" },
  { "id": "7585", "name": "Steve Hunt", "position": "L" },
  { "id": "6953", "name": "Steve Jugloff", "position": "L" },
  { "id": "6816", "name": "Steven Comparelli", "position": "J" },
  { "id": "6919", "name": "Stewart Martins", "position": "La" },
  { "id": "7775", "name": "Tiago Martins", "position": "J" },
  { "id": "8253", "name": "Torin R Henderson", "position": "Pa" },
  { "id": "7991", "name": "Tyler Zita", "position": "A1-16.5" },
  { "id": "8366", "name": "Umakanthan Sivagnanasundaram", "position": "J" },
  { "id": "8205", "name": "Viacheslav Derun", "position": "Lap3" },
  { "id": "7233", "name": "Victor Vitales", "position": "G" },
  { "id": "7786", "name": "William Rideout", "position": "A3-49.5" },
  { "id": "7739", "name": "Zachary M Holloway", "position": "F" }
];

var SEED_PROJECTS = [
  { "id": "31115", "label": "2014 Western Star 4900 Hydro Excavator", "isRetrofit": false },
  { "id": "H00441", "label": "Hurontario LRT, Temporary Traffic Signal", "isRetrofit": false },
  { "id": "H00925", "label": "MTO 2024-2011, QEW Burlington Skyway", "isRetrofit": false },
  { "id": "H00940", "label": "Lakeshore West Buloak Grade Separation", "isRetrofit": false },
  { "id": "H01027", "label": "Burlington Prospect St area phase 1 Minor reconstruction, watermain and waste installation", "isRetrofit": false },
  { "id": "H01091", "label": "Burlington Prospect St Area Phase 2", "isRetrofit": false },
  { "id": "TMH00251", "label": "Traffic Signals Mississauga Emergency Maint PRC005227", "isRetrofit": true }
];
